config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'welcome/index'
  
  resources :tasks do
    resources :comments
  end
  resources :users, :sessions
  resources :articles, as: 'articles'
  

  root 'tasks#index'
  match "*path", via: [:get, :post], :to => "errors#not_found"

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  accepts_nested_attributes_for :user
  #attr_accessible :title, :text

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  validates_presence_of :role
  has_many :tasks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  

  def if_user
  	redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  
  def if_admin
    redirect_to root_url, alert: "Not admin" if current_user.nil? || current_user.role != 1
  end

  def if_current_user
    ids = current_user.id.to_s + " | " + params[:id]
    redirect_to root_url, alert: "User have no permissons #{ids}" if current_user.id!=(params[:id])
  end
  
  def admin?
    !current_user.nil? && User.find(session[:user_id]).role == 1
  end
  helper_method :admin?

  rescue_from ActiveRecord::RecordNotFound, :with => :error_not_found
  rescue_from AbstractController::ActionNotFound, :with => :error_not_found
  rescue_from ActionView::MissingTemplate, :with => :error_not_found

  def error_not_found
  render :status => 404, :template => 'errors/not_found', :layout => 'errors'
  end
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
    before_action :if_admin, except: [:index, :show]
    
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end
    
    def new
        @article = Article.new
    end
    
    def edit
    
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to articles_path
        else
            render 'new'
        end
    end
    
    def update
    
    end
    
    def destroy
    
    end
    
    private
    def article_params
        params.require(:article).permit(:title, :text) 
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @task = Task.find(params[:task_id])
    @comment = @task.comments.create(comment_params)
    redirect_to task_path(@task)
  end
  
  def destroy
    @task = Task.find(params[:task_id])
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to task_path(@task)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    key = Rails.env.development? ? :login : :email
    hash = {key => params[key]}

    user = User.find_by(hash)

  	if user && (Rails.env.development? || user.authenticate(params[:password]))
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged in"
  	else
  		flash[:alert] = "Email or password is invalid"
  		render "new"
  	end

  end
  def destroy
  	session[:user_id] = nil
  	redirect_to root_url, notice: "logged off"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  

  before_filter :if_user, only: [:edit, :update, :show, :new, :edit, :destroy, :index]
  before_filter :if_admin, only: [:edit, :update]

  
  def index
    @tasks = Task.includes(:user)    
    
  end
  
  def show
    @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
    @task.user = current_user
  end

  def edit
    @task = Task.includes(:user).find(params[:id])    
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user

    if @task.save
      redirect_to tasks_path #@task
    else
      render 'new'
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to @task
    else
      render 'edit'
    end
  end  

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title, :text)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :if_user
  before_action :if_admin, only: [:index, :destroy]
  before_action :if_current_user, only: [:show, :edit, :update]
  #index, show, new, edit, create, update и destroy isnecud
    
  def index
    @users = User.all
  end
    
  def show
    @user = User.find(params[:id])   
  end

  def new 
    @user = User.new
  end
  
  def edit
     @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up"
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])  
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end


  def destroy
  
  end

end

private
def user_params
  params.require(:user).permit(:name, :login, :password, :email, :password_confirmation, :role)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.slim
h1
  | Articles
- @articles.each do |a|
  h3
    = a.title
  p
    = a.text

app/views/articles/new.html.slim
h1
  | Article new
= form_for @article do |f|
  = f.label :title
  = f.text_field :title
  = f.label :text
  = f.text_area :text
  = f.submit "Submit"

app/views/comments/_comment.html.slim
p
  strong
    | Commenter:
  = comment.commenter
p
  strong
    | Comment:
  = comment.body
p
  = link_to 'Destroy Comment', [comment.task, comment],
                  method: :delete,
                  data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.slim
= form_for([@task, @task.comments.build]) do |f|
  p
    = f.label :commenter
    br
    = f.text_field :commenter
  p
    = f.label :body
    br
    = f.text_area :body
  p
    = f.submit

app/views/layouts/_menu.html.slim
nav.top-bar[data-topbar role="navigation"]
  ul.title-area
    li.name
      h1
        a[href="#"]
          | h_desk
  section.top-bar-section
    ul.right
      li
        = link_to 'Пользователи', users_path if admin?
      li
        = link_to 'База знаний', articles_path
      li
        = link_to 'Заявки', tasks_path
      li.has-dropdown
        a[href="#"]
          | Отчеты
        ul.dropdown
          li
            a[href="#"]
              | Отчет за месяц
          li
            a[href="#"]
              | Незакрытые заявки
      - if current_user
        li[style="color: #008cba; margin-top: 13px; font-weight: bold; font-size: 0.8125rem;"]
          | Logged as
          = current_user.login
        li
          = link_to 'Log out', logout_path
      - else
        li
          = link_to 'Sign Up', signup_path
        li
          = link_to 'Log In', login_path

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "H_Desk"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  body
    .row
      .12-columns
        = render "layouts/menu"
        - flash.each do |name, msg|
          = content_tag :div, msg, id: "flash_#{name}"
        = yield
        = javascript_include_tag "application"

app/views/tasks/_form.html.slim
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h2
        = pluralize(@task.errors.count, "error")
        |  prohibited this task from being saved:
      ul
        - @task.errors.full_messages.each do |msg|
          li
            = msg
  p
    = @task.user
  p
    = f.label :title
    br
    = f.text_field :title
    br
  p
    = f.label :text
    br
    = f.text_area :text
  p
    = f.submit

app/views/tasks/edit.html.slim
h1
   | Edit task

= debug @current_user

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/index.html.slim
= link_to 'Подать заявку', new_task_path, class: "button small"
table
  tr
    th
      | Title
    th
      | Text
    th
      | User
  - @tasks.each do |task|
    tr
      td
        = task.title
      td
        = task.text
      td
        = task.user.name
      td
        = link_to 'Show', task_path(task)
      td
        = link_to 'Edit', edit_task_path(task)
      td
        = link_to 'Destroy', task_path(task),
          method: :delete,
          data: { confirm: 'Are you sure?' }

app/views/tasks/new.html.slim
h1
  | New task
= render 'form'
= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p
  strong
    | Title:
  = @task.title
p
  strong
    | Text:
  = @task.text
h2
  | Comments
= render @task.comments
h2
  | Add a comment:
= render 'comments/form'
= link_to 'Back', tasks_path
= link_to 'Edit', edit_task_path(@task)

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :login %>
<%= f.text_field :login %>
<%= f.label :password %>
<%= f.text_field :password %>
<%= f.label :email %>
<%= f.text_field :email%>
<%= f.submit "Submit" %>

<% end %>
    

app/views/users/edit.html.slim
h1
  | Edit User
= form_for @user do |f|
  = f.label :name
  = f.text_field :name
  = f.label :login
  = f.text_field :login
  = f.label :password
  = f.text_field :password
  = f.label :email
  = f.text_field :email
  = f.submit "Submit"

app/views/users/index.html.erb
<h1>Users list</h1>
<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Имя</th>
      <th>Логин</th>
      <th>Пароль</th>
      <th>Email</th>
      <th>Role</th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.login %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to "Show", user_path(user) %></td>
        <td><%= link_to "Edit", edit_user_path(user) %></td>
        <td><%= link_to "Delete", user_path(user), 
        method: :destroy,
        data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.slim
h1
  | Users list
table
  thead
    tr
      th
        | id
      th
        | Имя
      th
        | Логин
      th
        | Пароль
      th
        | Email
      th
        | Role
      th

      th

      th

  tbody
    - @users.each do |user|
      tr
        td
          = user.id
        td
          = user.name
        td
          = user.login
        td
          = user.password
        td
          = user.email
        td
          = user.role
        td
          = link_to "Show", user_path(user)
        td
          = link_to "Edit", edit_user_path(user)
        td
          = link_to "Delete", user_path(user),
             method: :destroy,
             data: { confirm: 'Are you sure?' }

app/views/users/new.html.erb
<h1> sign up </h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_mesages">
      <h2>Form is invalid</h2>
        <ul>
          <%= @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :login %><br />
  <%= f.text_field :login %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>
<div class="field">
  <%= f.radio_button :role, 2, :checked => true %> 
  <%= label :role_user, 'User' %>
  <%= f.radio_button :role, 1 %>
  <%= label :role_admin, 'Admin' %>

</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

app/views/users/new.html.slim
h1
  |  sign up
= form_for @user do |f|
  - if @user.errors.any?
    .error_mesages
      h2
        | Form is invalid
      ul
        = @user.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :login
    br
    = f.text_field :login
  .field
    = f.label :email
    br
    = f.text_field :email
  .field
    = f.label :password
    br
    = f.password_field :password
  .field
    = f.label :password_confirmation
    br
    = f.password_field :password_confirmation
  .field
    = f.radio_button :role, 2, :checked => true
    = label :role_user, 'User'
    = f.radio_button :role, 1
    = label :role_admin, 'Admin'
  .actions
    = f.submit

app/views/users/show.html.erb
<h1>Show user #<%= @user.id %> </h1>
<p>User name: <%= @user.name %></p>
<br />
<p>Login: <%= @user.login %></p>
<br />
<p>Password: <%= @user.password %></p>
<br />
<p>Email: <%= @user.email %></p>

app/views/users/show.html.slim
h1
  | Show user #
  = @user.id
p
  | User name:
  = @user.name
br
p
  | Login:
  = @user.login
br
p
  | Password:
  = @user.password
br
p
  | Email:
  = @user.email

app/views/welcome/index.html.erb
<h1>Welcome to h_desk!</h1>
<%= link_to 'view tickets', controller: 'tasks' %>

app/views/welcome/index.html.slim
h1
  | Welcome to h_desk!
= link_to 'view tickets',
  controller: 'tasks'